import openpyxl as xl
from settings import INVOICES_FOLDER, MANAGEMENT
from Occupant import Occupant
import inv_tracker as it
import os
from datetime import datetime

it.maintain_current_new(it.open_invoice("september22.xlsx"), debug=True)
# it.clean_with_end_date(it.full_populate(), it.open_invoice("september22.xlsx"))

# DATA IS NOT PROPERLY CLEANED
# ADDING ROWS FOR 13 ST AUGUSTINE AVE... NOT WORKING DUE TO INCONSISTENCY WITH ADDRESS
# SOME ROWS SHOULD'VE BEEN ADDED IN PREVIOUS INVOICE BUT NOT ADDED
# FIX POTENTIAL FORMATTING ISSUES?
#THERE IS A HIGH CHANCE THAT NEW ADDED ROWS,CHNAGED ROWS, DELETED ROWS HAVE NOT BEEN COMPLETED PROPERLY
# CHECK CROSS REFERENCE AND CHECK AGAIN TO CRITERIA
# CAN'T DO PROPER COMPARISON BERTWEEN TRACKER AND INVOICE - SOME DATA IS MISSING FROM BOTH
#   THIS MEANS THAT WE NEED MORE CODE TO SEE CHANGES AND SEE IF IT CORRECT FOR THAT ROW

# MAIN - DEVELOP CODE OR SEE IF DATA HAS BEEN ADDED, MODIFIED OR DELETED PROPERLY
# I AM 99% SURE THAT THESE THREE STEPS IN THE PROCESS HAS NOT FULLY COMPLETED ITS TASKS
# DUE TO REASONS GIVEN OR THOSE NOT YET FOUND/FORGOTTEN